[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding.x = 10
padding.y = 10
startup_mode = "Maximized"  # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"

decorations = "Buttonless"

opacity = 0.95
blur = true

[font]
normal.family = "DejaVu Sans Mono"
size = 14